#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
# jupyter labextension install @jupyterlab/geojson-extension@0.16.0 jupyterlab-drawio
jupyter labextension install @jupyterlab/jupyterlab-drawio

# Install from Source
git clone https://github.com/jupyterlab/jupyter-renderers.git
cd jupyter-renderers

# Install dependencies 
jlpm

# Build Typescript source 
jlpm build

# Link your development version of the extension with JupyterLab 
jupyter labextension link packages/geojson-extension

# Rebuild Typescript source after making changes 
jlpm build

# Rebuild JupyterLab after making any changes 
jupyter lab build
